-- ================================================================
-- subjects_seed.sql — generated from timetable_all_semesters.csv
-- Run in MySQL Workbench: USE college_portal; then run this file
-- ================================================================

USE college_portal;

-- Clear existing subjects to avoid duplicates
TRUNCATE TABLE subjects;

INSERT INTO subjects (subject_code, subject_name, branch, semester, credits) VALUES
  ('BEE', 'Basic Electrical Engineering', 'CIVIL', 1, 3),
  ('CHEM', 'Engineering Chemistry', 'CIVIL', 1, 3),
  ('ENG', 'Eng', 'CIVIL', 1, 3),
  ('MATH-I', 'Mathematics I', 'CIVIL', 1, 3),
  ('PHYSICS', 'Physics', 'CIVIL', 1, 3),
  ('PPS', 'Problem Solving & Python Programming', 'CIVIL', 1, 3),
  ('WS', 'Workshop Practice', 'CIVIL', 1, 3),
  ('BCS', 'Basic Computer Science', 'CIVIL', 2, 3),
  ('CHEMISTRY', 'Chemistry', 'CIVIL', 2, 3),
  ('DS', 'Data Structures', 'CIVIL', 2, 3),
  ('EG', 'Engineering Graphics', 'CIVIL', 2, 3),
  ('ENG', 'Eng', 'CIVIL', 2, 3),
  ('EVS', 'Evs', 'CIVIL', 2, 3),
  ('MATH-II', 'Mathematics II', 'CIVIL', 2, 3),
  ('COA', 'Computer Organization & Architecture', 'CIVIL', 3, 3),
  ('DBMS', 'Database Management Systems', 'CIVIL', 3, 3),
  ('DLD', 'Dld', 'CIVIL', 3, 3),
  ('DS', 'Data Structures', 'CIVIL', 3, 3),
  ('ENG', 'Eng', 'CIVIL', 3, 3),
  ('MATH-III', 'Mathematics III', 'CIVIL', 3, 3),
  ('OOP', 'Oop', 'CIVIL', 3, 3),
  ('ADA', 'Ada', 'CIVIL', 4, 3),
  ('CN', 'Computer Networks', 'CIVIL', 4, 3),
  ('DBMS-LAB', 'Dbms-Lab', 'CIVIL', 4, 2),
  ('MP', 'Microprocessors', 'CIVIL', 4, 3),
  ('OS', 'Operating Systems', 'CIVIL', 4, 3),
  ('SE', 'Software Engineering', 'CIVIL', 4, 3),
  ('TOC', 'Theory of Computation', 'CIVIL', 4, 3),
  ('AI', 'Artificial Intelligence', 'CIVIL', 5, 3),
  ('CD', 'Compiler Design', 'CIVIL', 5, 3),
  ('CN-II', 'Cn-Ii', 'CIVIL', 5, 3),
  ('ML', 'Machine Learning', 'CIVIL', 5, 3),
  ('SE-II', 'Se-Ii', 'CIVIL', 5, 3),
  ('SEMINAR', 'Seminar', 'CIVIL', 5, 2),
  ('WD', 'Web Development', 'CIVIL', 5, 3),
  ('CC', 'Cloud Computing', 'CIVIL', 6, 3),
  ('DWM', 'Dwm', 'CIVIL', 6, 3),
  ('IOT', 'Internet of Things', 'CIVIL', 6, 3),
  ('IS', 'Information Security', 'CIVIL', 6, 3),
  ('NLP', 'Natural Language Processing', 'CIVIL', 6, 3),
  ('PROJECT', 'Project Phase', 'CIVIL', 6, 6),
  ('SEMINAR', 'Seminar', 'CIVIL', 6, 2),
  ('CL&E', 'Cloud & Edge Computing', 'CIVIL', 7, 2),
  ('DIP', 'Digital Image Processing', 'CIVIL', 7, 3),
  ('ED', 'Entrepreneurship Development', 'CIVIL', 7, 3),
  ('IOT', 'Internet of Things', 'CIVIL', 7, 3),
  ('RPGS', 'Research Paper & Graduate Seminar', 'CIVIL', 7, 2),
  ('SEMINAR', 'Seminar', 'CIVIL', 7, 2),
  ('SPM', 'Software Project Management', 'CIVIL', 7, 3),
  ('ELEC-I', 'Elective I', 'CIVIL', 8, 3),
  ('ELEC-II', 'Elective II', 'CIVIL', 8, 3),
  ('INTERN', 'Internship', 'CIVIL', 8, 2),
  ('PROJECT', 'Project Phase', 'CIVIL', 8, 6),
  ('SEMINAR', 'Seminar', 'CIVIL', 8, 2),
  ('THESIS', 'Thesis', 'CIVIL', 8, 6),
  ('VIVA', 'Comprehensive Viva', 'CIVIL', 8, 2),
  ('AI', 'Artificial Intelligence', 'CS-AIML', 5, 3),
  ('CD', 'Compiler Design', 'CS-AIML', 5, 3),
  ('CN-II', 'Cn-Ii', 'CS-AIML', 5, 3),
  ('ML', 'Machine Learning', 'CS-AIML', 5, 3),
  ('SE-II', 'Se-Ii', 'CS-AIML', 5, 3),
  ('SEMINAR', 'Seminar', 'CS-AIML', 5, 2),
  ('WD', 'Web Development', 'CS-AIML', 5, 3),
  ('CC', 'Cloud Computing', 'CS-AIML', 6, 3),
  ('DWM', 'Dwm', 'CS-AIML', 6, 3),
  ('IOT', 'Internet of Things', 'CS-AIML', 6, 3),
  ('IS', 'Information Security', 'CS-AIML', 6, 3),
  ('NLP', 'Natural Language Processing', 'CS-AIML', 6, 3),
  ('PROJECT', 'Project Phase', 'CS-AIML', 6, 6),
  ('SEMINAR', 'Seminar', 'CS-AIML', 6, 2),
  ('CL&E', 'Cloud & Edge Computing', 'CS-AIML', 7, 2),
  ('DIP', 'Digital Image Processing', 'CS-AIML', 7, 3),
  ('ED', 'Entrepreneurship Development', 'CS-AIML', 7, 3),
  ('IOT', 'Internet of Things', 'CS-AIML', 7, 3),
  ('RPGS', 'Research Paper & Graduate Seminar', 'CS-AIML', 7, 2),
  ('SEMINAR', 'Seminar', 'CS-AIML', 7, 2),
  ('SPM', 'Software Project Management', 'CS-AIML', 7, 3),
  ('COA', 'Computer Organization & Architecture', 'CS-IT', 3, 3),
  ('DBMS', 'Database Management Systems', 'CS-IT', 3, 3),
  ('DLD', 'Dld', 'CS-IT', 3, 3),
  ('DS', 'Data Structures', 'CS-IT', 3, 3),
  ('ENG', 'Eng', 'CS-IT', 3, 3),
  ('MATH-III', 'Mathematics III', 'CS-IT', 3, 3),
  ('OOP', 'Oop', 'CS-IT', 3, 3),
  ('ADA', 'Ada', 'CS-IT', 4, 3),
  ('CN', 'Computer Networks', 'CS-IT', 4, 3),
  ('DBMS-LAB', 'Dbms-Lab', 'CS-IT', 4, 2),
  ('MP', 'Microprocessors', 'CS-IT', 4, 3),
  ('OS', 'Operating Systems', 'CS-IT', 4, 3),
  ('SE', 'Software Engineering', 'CS-IT', 4, 3),
  ('TOC', 'Theory of Computation', 'CS-IT', 4, 3),
  ('AI', 'Artificial Intelligence', 'CS-IT', 5, 3),
  ('CD', 'Compiler Design', 'CS-IT', 5, 3),
  ('CN-II', 'Cn-Ii', 'CS-IT', 5, 3),
  ('ML', 'Machine Learning', 'CS-IT', 5, 3),
  ('SE-II', 'Se-Ii', 'CS-IT', 5, 3),
  ('SEMINAR', 'Seminar', 'CS-IT', 5, 2),
  ('WD', 'Web Development', 'CS-IT', 5, 3),
  ('CC', 'Cloud Computing', 'CS-IT', 6, 3),
  ('DWM', 'Dwm', 'CS-IT', 6, 3),
  ('IOT', 'Internet of Things', 'CS-IT', 6, 3),
  ('IS', 'Information Security', 'CS-IT', 6, 3),
  ('NLP', 'Natural Language Processing', 'CS-IT', 6, 3),
  ('PROJECT', 'Project Phase', 'CS-IT', 6, 6),
  ('SEMINAR', 'Seminar', 'CS-IT', 6, 2),
  ('CL&E', 'Cloud & Edge Computing', 'CS-IT', 7, 2),
  ('DIP', 'Digital Image Processing', 'CS-IT', 7, 3),
  ('ED', 'Entrepreneurship Development', 'CS-IT', 7, 3),
  ('IOT', 'Internet of Things', 'CS-IT', 7, 3),
  ('RPGS', 'Research Paper & Graduate Seminar', 'CS-IT', 7, 2),
  ('SEMINAR', 'Seminar', 'CS-IT', 7, 2),
  ('SPM', 'Software Project Management', 'CS-IT', 7, 3),
  ('ELEC-I', 'Elective I', 'CS-IT', 8, 3),
  ('ELEC-II', 'Elective II', 'CS-IT', 8, 3),
  ('INTERN', 'Internship', 'CS-IT', 8, 2),
  ('PROJECT', 'Project Phase', 'CS-IT', 8, 6),
  ('SEMINAR', 'Seminar', 'CS-IT', 8, 2),
  ('THESIS', 'Thesis', 'CS-IT', 8, 6),
  ('VIVA', 'Comprehensive Viva', 'CS-IT', 8, 2),
  ('BEE', 'Basic Electrical Engineering', 'CSE', 1, 3),
  ('CHEM', 'Engineering Chemistry', 'CSE', 1, 3),
  ('ENG', 'Eng', 'CSE', 1, 3),
  ('MATH-I', 'Mathematics I', 'CSE', 1, 3),
  ('PHYSICS', 'Physics', 'CSE', 1, 3),
  ('PPS', 'Problem Solving & Python Programming', 'CSE', 1, 3),
  ('WS', 'Workshop Practice', 'CSE', 1, 3),
  ('BCS', 'Basic Computer Science', 'CSE', 2, 3),
  ('CHEMISTRY', 'Chemistry', 'CSE', 2, 3),
  ('DS', 'Data Structures', 'CSE', 2, 3),
  ('EG', 'Engineering Graphics', 'CSE', 2, 3),
  ('ENG', 'Eng', 'CSE', 2, 3),
  ('EVS', 'Evs', 'CSE', 2, 3),
  ('MATH-II', 'Mathematics II', 'CSE', 2, 3),
  ('COA', 'Computer Organization & Architecture', 'CSE', 3, 3),
  ('DBMS', 'Database Management Systems', 'CSE', 3, 3),
  ('DLD', 'Dld', 'CSE', 3, 3),
  ('DS', 'Data Structures', 'CSE', 3, 3),
  ('ENG', 'Eng', 'CSE', 3, 3),
  ('MATH-III', 'Mathematics III', 'CSE', 3, 3),
  ('OOP', 'Oop', 'CSE', 3, 3),
  ('ADA', 'Ada', 'CSE', 4, 3),
  ('CN', 'Computer Networks', 'CSE', 4, 3),
  ('DBMS-LAB', 'Dbms-Lab', 'CSE', 4, 2),
  ('MP', 'Microprocessors', 'CSE', 4, 3),
  ('OS', 'Operating Systems', 'CSE', 4, 3),
  ('SE', 'Software Engineering', 'CSE', 4, 3),
  ('TOC', 'Theory of Computation', 'CSE', 4, 3),
  ('AI', 'Artificial Intelligence', 'CSE', 5, 3),
  ('CD', 'Compiler Design', 'CSE', 5, 3),
  ('CN-II', 'Cn-Ii', 'CSE', 5, 3),
  ('ML', 'Machine Learning', 'CSE', 5, 3),
  ('SE-II', 'Se-Ii', 'CSE', 5, 3),
  ('SEMINAR', 'Seminar', 'CSE', 5, 2),
  ('WD', 'Web Development', 'CSE', 5, 3),
  ('CC', 'Cloud Computing', 'CSE', 6, 3),
  ('DWM', 'Dwm', 'CSE', 6, 3),
  ('IOT', 'Internet of Things', 'CSE', 6, 3),
  ('IS', 'Information Security', 'CSE', 6, 3),
  ('NLP', 'Natural Language Processing', 'CSE', 6, 3),
  ('PROJECT', 'Project Phase', 'CSE', 6, 6),
  ('SEMINAR', 'Seminar', 'CSE', 6, 2),
  ('CL&E', 'Cloud & Edge Computing', 'CSE', 7, 2),
  ('DIP', 'Digital Image Processing', 'CSE', 7, 3),
  ('ED', 'Entrepreneurship Development', 'CSE', 7, 3),
  ('IOT', 'Internet of Things', 'CSE', 7, 3),
  ('RPGS', 'Research Paper & Graduate Seminar', 'CSE', 7, 2),
  ('SEMINAR', 'Seminar', 'CSE', 7, 2),
  ('SPM', 'Software Project Management', 'CSE', 7, 3),
  ('ELEC-I', 'Elective I', 'CSE', 8, 3),
  ('ELEC-II', 'Elective II', 'CSE', 8, 3),
  ('INTERN', 'Internship', 'CSE', 8, 2),
  ('PROJECT', 'Project Phase', 'CSE', 8, 6),
  ('SEMINAR', 'Seminar', 'CSE', 8, 2),
  ('THESIS', 'Thesis', 'CSE', 8, 6),
  ('VIVA', 'Comprehensive Viva', 'CSE', 8, 2),
  ('BEE', 'Basic Electrical Engineering', 'CST', 1, 3),
  ('CHEM', 'Engineering Chemistry', 'CST', 1, 3),
  ('ENG', 'Eng', 'CST', 1, 3),
  ('MATH-I', 'Mathematics I', 'CST', 1, 3),
  ('PHYSICS', 'Physics', 'CST', 1, 3),
  ('PPS', 'Problem Solving & Python Programming', 'CST', 1, 3),
  ('WS', 'Workshop Practice', 'CST', 1, 3),
  ('BCS', 'Basic Computer Science', 'CST', 2, 3),
  ('CHEMISTRY', 'Chemistry', 'CST', 2, 3),
  ('DS', 'Data Structures', 'CST', 2, 3),
  ('EG', 'Engineering Graphics', 'CST', 2, 3),
  ('ENG', 'Eng', 'CST', 2, 3),
  ('EVS', 'Evs', 'CST', 2, 3),
  ('MATH-II', 'Mathematics II', 'CST', 2, 3),
  ('COA', 'Computer Organization & Architecture', 'CST', 3, 3),
  ('DBMS', 'Database Management Systems', 'CST', 3, 3),
  ('DLD', 'Dld', 'CST', 3, 3),
  ('DS', 'Data Structures', 'CST', 3, 3),
  ('ENG', 'Eng', 'CST', 3, 3),
  ('MATH-III', 'Mathematics III', 'CST', 3, 3),
  ('OOP', 'Oop', 'CST', 3, 3),
  ('ADA', 'Ada', 'CST', 4, 3),
  ('CN', 'Computer Networks', 'CST', 4, 3),
  ('DBMS-LAB', 'Dbms-Lab', 'CST', 4, 2),
  ('MP', 'Microprocessors', 'CST', 4, 3),
  ('OS', 'Operating Systems', 'CST', 4, 3),
  ('SE', 'Software Engineering', 'CST', 4, 3),
  ('TOC', 'Theory of Computation', 'CST', 4, 3),
  ('AI', 'Artificial Intelligence', 'CST', 5, 3),
  ('CD', 'Compiler Design', 'CST', 5, 3),
  ('CN-II', 'Cn-Ii', 'CST', 5, 3),
  ('ML', 'Machine Learning', 'CST', 5, 3),
  ('SE-II', 'Se-Ii', 'CST', 5, 3),
  ('SEMINAR', 'Seminar', 'CST', 5, 2),
  ('WD', 'Web Development', 'CST', 5, 3),
  ('CC', 'Cloud Computing', 'CST', 6, 3),
  ('DWM', 'Dwm', 'CST', 6, 3),
  ('IOT', 'Internet of Things', 'CST', 6, 3),
  ('IS', 'Information Security', 'CST', 6, 3),
  ('NLP', 'Natural Language Processing', 'CST', 6, 3),
  ('PROJECT', 'Project Phase', 'CST', 6, 6),
  ('SEMINAR', 'Seminar', 'CST', 6, 2),
  ('CL&E', 'Cloud & Edge Computing', 'CST', 7, 2),
  ('DIP', 'Digital Image Processing', 'CST', 7, 3),
  ('ED', 'Entrepreneurship Development', 'CST', 7, 3),
  ('IOT', 'Internet of Things', 'CST', 7, 3),
  ('RPGS', 'Research Paper & Graduate Seminar', 'CST', 7, 2),
  ('SEMINAR', 'Seminar', 'CST', 7, 2),
  ('SPM', 'Software Project Management', 'CST', 7, 3),
  ('ELEC-I', 'Elective I', 'CST', 8, 3),
  ('ELEC-II', 'Elective II', 'CST', 8, 3),
  ('INTERN', 'Internship', 'CST', 8, 2),
  ('PROJECT', 'Project Phase', 'CST', 8, 6),
  ('SEMINAR', 'Seminar', 'CST', 8, 2),
  ('THESIS', 'Thesis', 'CST', 8, 6),
  ('VIVA', 'Comprehensive Viva', 'CST', 8, 2),
  ('BEE', 'Basic Electrical Engineering', 'EEE', 1, 3),
  ('CHEM', 'Engineering Chemistry', 'EEE', 1, 3),
  ('ENG', 'Eng', 'EEE', 1, 3),
  ('MATH-I', 'Mathematics I', 'EEE', 1, 3),
  ('PHYSICS', 'Physics', 'EEE', 1, 3),
  ('PPS', 'Problem Solving & Python Programming', 'EEE', 1, 3),
  ('WS', 'Workshop Practice', 'EEE', 1, 3),
  ('BCS', 'Basic Computer Science', 'EEE', 2, 3),
  ('CHEMISTRY', 'Chemistry', 'EEE', 2, 3),
  ('DS', 'Data Structures', 'EEE', 2, 3),
  ('EG', 'Engineering Graphics', 'EEE', 2, 3),
  ('ENG', 'Eng', 'EEE', 2, 3),
  ('EVS', 'Evs', 'EEE', 2, 3),
  ('MATH-II', 'Mathematics II', 'EEE', 2, 3),
  ('COA', 'Computer Organization & Architecture', 'EEE', 3, 3),
  ('DBMS', 'Database Management Systems', 'EEE', 3, 3),
  ('DLD', 'Dld', 'EEE', 3, 3),
  ('DS', 'Data Structures', 'EEE', 3, 3),
  ('ENG', 'Eng', 'EEE', 3, 3),
  ('MATH-III', 'Mathematics III', 'EEE', 3, 3),
  ('OOP', 'Oop', 'EEE', 3, 3),
  ('ADA', 'Ada', 'EEE', 4, 3),
  ('CN', 'Computer Networks', 'EEE', 4, 3),
  ('DBMS-LAB', 'Dbms-Lab', 'EEE', 4, 2),
  ('MP', 'Microprocessors', 'EEE', 4, 3),
  ('OS', 'Operating Systems', 'EEE', 4, 3),
  ('SE', 'Software Engineering', 'EEE', 4, 3),
  ('TOC', 'Theory of Computation', 'EEE', 4, 3),
  ('AI', 'Artificial Intelligence', 'EEE', 5, 3),
  ('CD', 'Compiler Design', 'EEE', 5, 3),
  ('CN-II', 'Cn-Ii', 'EEE', 5, 3),
  ('ML', 'Machine Learning', 'EEE', 5, 3),
  ('SE-II', 'Se-Ii', 'EEE', 5, 3),
  ('SEMINAR', 'Seminar', 'EEE', 5, 2),
  ('WD', 'Web Development', 'EEE', 5, 3),
  ('CC', 'Cloud Computing', 'EEE', 6, 3),
  ('DWM', 'Dwm', 'EEE', 6, 3),
  ('IOT', 'Internet of Things', 'EEE', 6, 3),
  ('IS', 'Information Security', 'EEE', 6, 3),
  ('NLP', 'Natural Language Processing', 'EEE', 6, 3),
  ('PROJECT', 'Project Phase', 'EEE', 6, 6),
  ('SEMINAR', 'Seminar', 'EEE', 6, 2),
  ('CL&E', 'Cloud & Edge Computing', 'EEE', 7, 2),
  ('DIP', 'Digital Image Processing', 'EEE', 7, 3),
  ('ED', 'Entrepreneurship Development', 'EEE', 7, 3),
  ('IOT', 'Internet of Things', 'EEE', 7, 3),
  ('RPGS', 'Research Paper & Graduate Seminar', 'EEE', 7, 2),
  ('SEMINAR', 'Seminar', 'EEE', 7, 2),
  ('SPM', 'Software Project Management', 'EEE', 7, 3),
  ('ELEC-I', 'Elective I', 'EEE', 8, 3),
  ('ELEC-II', 'Elective II', 'EEE', 8, 3),
  ('INTERN', 'Internship', 'EEE', 8, 2),
  ('PROJECT', 'Project Phase', 'EEE', 8, 6),
  ('SEMINAR', 'Seminar', 'EEE', 8, 2),
  ('THESIS', 'Thesis', 'EEE', 8, 6),
  ('VIVA', 'Comprehensive Viva', 'EEE', 8, 2),
  ('BEE', 'Basic Electrical Engineering', 'ETC', 1, 3),
  ('CHEM', 'Engineering Chemistry', 'ETC', 1, 3),
  ('ENG', 'Eng', 'ETC', 1, 3),
  ('MATH-I', 'Mathematics I', 'ETC', 1, 3),
  ('PHYSICS', 'Physics', 'ETC', 1, 3),
  ('PPS', 'Problem Solving & Python Programming', 'ETC', 1, 3),
  ('WS', 'Workshop Practice', 'ETC', 1, 3),
  ('BCS', 'Basic Computer Science', 'ETC', 2, 3),
  ('CHEMISTRY', 'Chemistry', 'ETC', 2, 3),
  ('DS', 'Data Structures', 'ETC', 2, 3),
  ('EG', 'Engineering Graphics', 'ETC', 2, 3),
  ('ENG', 'Eng', 'ETC', 2, 3),
  ('EVS', 'Evs', 'ETC', 2, 3),
  ('MATH-II', 'Mathematics II', 'ETC', 2, 3),
  ('COA', 'Computer Organization & Architecture', 'ETC', 3, 3),
  ('DBMS', 'Database Management Systems', 'ETC', 3, 3),
  ('DLD', 'Dld', 'ETC', 3, 3),
  ('DS', 'Data Structures', 'ETC', 3, 3),
  ('ENG', 'Eng', 'ETC', 3, 3),
  ('MATH-III', 'Mathematics III', 'ETC', 3, 3),
  ('OOP', 'Oop', 'ETC', 3, 3),
  ('ADA', 'Ada', 'ETC', 4, 3),
  ('CN', 'Computer Networks', 'ETC', 4, 3),
  ('DBMS-LAB', 'Dbms-Lab', 'ETC', 4, 2),
  ('MP', 'Microprocessors', 'ETC', 4, 3),
  ('OS', 'Operating Systems', 'ETC', 4, 3),
  ('SE', 'Software Engineering', 'ETC', 4, 3),
  ('TOC', 'Theory of Computation', 'ETC', 4, 3),
  ('AI', 'Artificial Intelligence', 'ETC', 5, 3),
  ('CD', 'Compiler Design', 'ETC', 5, 3),
  ('CN-II', 'Cn-Ii', 'ETC', 5, 3),
  ('ML', 'Machine Learning', 'ETC', 5, 3),
  ('SE-II', 'Se-Ii', 'ETC', 5, 3),
  ('SEMINAR', 'Seminar', 'ETC', 5, 2),
  ('WD', 'Web Development', 'ETC', 5, 3),
  ('CC', 'Cloud Computing', 'ETC', 6, 3),
  ('DWM', 'Dwm', 'ETC', 6, 3),
  ('IOT', 'Internet of Things', 'ETC', 6, 3),
  ('IS', 'Information Security', 'ETC', 6, 3),
  ('NLP', 'Natural Language Processing', 'ETC', 6, 3),
  ('PROJECT', 'Project Phase', 'ETC', 6, 6),
  ('SEMINAR', 'Seminar', 'ETC', 6, 2),
  ('CL&E', 'Cloud & Edge Computing', 'ETC', 7, 2),
  ('DIP', 'Digital Image Processing', 'ETC', 7, 3),
  ('ED', 'Entrepreneurship Development', 'ETC', 7, 3),
  ('IOT', 'Internet of Things', 'ETC', 7, 3),
  ('RPGS', 'Research Paper & Graduate Seminar', 'ETC', 7, 2),
  ('SEMINAR', 'Seminar', 'ETC', 7, 2),
  ('SPM', 'Software Project Management', 'ETC', 7, 3),
  ('ELEC-I', 'Elective I', 'ETC', 8, 3),
  ('ELEC-II', 'Elective II', 'ETC', 8, 3),
  ('INTERN', 'Internship', 'ETC', 8, 2),
  ('PROJECT', 'Project Phase', 'ETC', 8, 6),
  ('SEMINAR', 'Seminar', 'ETC', 8, 2),
  ('THESIS', 'Thesis', 'ETC', 8, 6),
  ('VIVA', 'Comprehensive Viva', 'ETC', 8, 2),
  ('BEE', 'Basic Electrical Engineering', 'MECH', 1, 3),
  ('CHEM', 'Engineering Chemistry', 'MECH', 1, 3),
  ('ENG', 'Eng', 'MECH', 1, 3),
  ('PHYSICS', 'Physics', 'MECH', 1, 3),
  ('PPS', 'Problem Solving & Python Programming', 'MECH', 1, 3),
  ('WS', 'Workshop Practice', 'MECH', 1, 3),
  ('BCS', 'Basic Computer Science', 'MECH', 2, 3),
  ('CHEMISTRY', 'Chemistry', 'MECH', 2, 3),
  ('DS', 'Data Structures', 'MECH', 2, 3),
  ('EG', 'Engineering Graphics', 'MECH', 2, 3),
  ('ENG', 'Eng', 'MECH', 2, 3),
  ('EVS', 'Evs', 'MECH', 2, 3),
  ('COA', 'Computer Organization & Architecture', 'MECH', 3, 3),
  ('DBMS', 'Database Management Systems', 'MECH', 3, 3),
  ('DLD', 'Dld', 'MECH', 3, 3),
  ('DS', 'Data Structures', 'MECH', 3, 3),
  ('ENG', 'Eng', 'MECH', 3, 3),
  ('OOP', 'Oop', 'MECH', 3, 3),
  ('ADA', 'Ada', 'MECH', 4, 3),
  ('CN', 'Computer Networks', 'MECH', 4, 3),
  ('DBMS-LAB', 'Dbms-Lab', 'MECH', 4, 2),
  ('MP', 'Microprocessors', 'MECH', 4, 3),
  ('OS', 'Operating Systems', 'MECH', 4, 3),
  ('SE', 'Software Engineering', 'MECH', 4, 3),
  ('AI', 'Artificial Intelligence', 'MECH', 5, 3),
  ('CN-II', 'Cn-Ii', 'MECH', 5, 3),
  ('ML', 'Machine Learning', 'MECH', 5, 3),
  ('SE-II', 'Se-Ii', 'MECH', 5, 3),
  ('SEMINAR', 'Seminar', 'MECH', 5, 2),
  ('WD', 'Web Development', 'MECH', 5, 3),
  ('CC', 'Cloud Computing', 'MECH', 6, 3),
  ('IOT', 'Internet of Things', 'MECH', 6, 3),
  ('IS', 'Information Security', 'MECH', 6, 3),
  ('NLP', 'Natural Language Processing', 'MECH', 6, 3),
  ('PROJECT', 'Project Phase', 'MECH', 6, 6),
  ('SEMINAR', 'Seminar', 'MECH', 6, 2),
  ('CL&E', 'Cloud & Edge Computing', 'MECH', 7, 2),
  ('DIP', 'Digital Image Processing', 'MECH', 7, 3),
  ('ED', 'Entrepreneurship Development', 'MECH', 7, 3),
  ('RPGS', 'Research Paper & Graduate Seminar', 'MECH', 7, 2),
  ('SEMINAR', 'Seminar', 'MECH', 7, 2),
  ('SPM', 'Software Project Management', 'MECH', 7, 3),
  ('ELEC-I', 'Elective I', 'MECH', 8, 3),
  ('ELEC-II', 'Elective II', 'MECH', 8, 3),
  ('INTERN', 'Internship', 'MECH', 8, 2),
  ('SEMINAR', 'Seminar', 'MECH', 8, 2),
  ('THESIS', 'Thesis', 'MECH', 8, 6),
  ('VIVA', 'Comprehensive Viva', 'MECH', 8, 2);

-- Total: 391 rows inserted
-- Verify with: SELECT branch, semester, COUNT(*) FROM subjects GROUP BY branch, semester ORDER BY branch, semester;